server:
  port: 8889
spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/mikasa123/config-mikasa.git
          default-label: master
          search-paths: config
management:
  endpoints:
    web:
      exposure:
        exclude: refresh
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
