eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
spring:
  application:
    name: config-client
management:
  endpoints:
    web:
      exposure:
        exclude: refresh